server.port=${SERVER_PORT:8080}
spring.profiles.active=${ACTIVE_PROFILE:mysql}

spring.application.name=back-end

spring.jackson.property-naming-strategy=SNAKE_CASE

jwt.validity=${JWT_VALIDITY}
jwt.secret=${JWT_SECRET}

plate.model.url=${URL_PYTHON:http://localhost:5000}

url.frontend=${URL_FRONTEND}

spring.cloud.compatibility-verifier.enabled=false

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:admin}
spring.rabbitmq.virtual-host=${SPRING_RABBITMQ_VHOST:/}


# AWS Real
aws.bucket.name=${AWS_BUCKET_NAME}
aws.accessKeyId=${AWS_ACCESS_KEY}
aws.secretAccessKey=${AWS_SECRET_ACCESS}
aws.sessionToken= ${AWS_SESSION_TOKEN}
aws.region=us-east-1