server:
  port: ${SERVER_PORT:8080}


jwt:
  validity: ${JWT_VALIDITY:86400}
  secret: ${JWT_SECRET:dev-secret-key-change-in-production }


plate:
  model:
    url: ${URL_PYTHON:http://localhost:5000}

url:
  frontend: ${URL_FRONTEND:http://localhost:5173}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/grotrack}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin}
    virtual-host: ${SPRING_RABBITMQ_VHOST:/}
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 1MB
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 0
      use-key-prefix: false

aws:
  s3:
    region: ${AWS_REGION:us-east-1}
    bucket-name: ${AWS_S3_BUCKET_NAME:grotrack-bucket}
    access-key: ${AWS_ACCESS_KEY_ID:test}
    secret-key: ${AWS_SECRET_ACCESS_KEY:test}
    endpoint-url: ${AWS_ENDPOINT_URL:http://127.0.0.1:4566}
    # session-token omitted

logging:
  level:
    org.springframework.cache.interceptor.CacheInterceptor: TRACE

