spring:
  profiles:
    active: dev
  application:
    name: back-end

  jackson:
    property-naming-strategy: SNAKE_CASE

  cloud:
    compatibility-verifier:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: back-end-grotrack