# ===== SERVER =====
server.port=${SERVER_PORT}

# ===== JWT =====
jwt.validity=${JWT_VALIDITY}
jwt.secret=${JWT_SECRET}

# ===== EXTERNAL SERVICES =====
plate.model.url=${URL_PYTHON}
# Multiple frontend URLs separated by comma
url.frontend=${URL_FRONTEND}

# ===== DATABASE =====
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# ===== RABBITMQ =====
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${SPRING_RABBITMQ_VHOST}

# ===== AWS S3 =====
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}
aws.s3.access-key=${AWS_ACCESS_KEY_ID}
aws.s3.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.s3.region=${AWS_REGION}
aws.s3.session-token=${AWS_SESSION_TOKEN}
aws.s3.endpoint-url=${AWS_ENDPOINT_URL}