server.port=${SERVER_PORT:8080}
spring.profiles.active=${ACTIVE_PROFILE:mysql}

spring.application.name=back-end

spring.jackson.property-naming-strategy=SNAKE_CASE

jwt.validity=${JWT_VALIDITY}
jwt.secret=${JWT_SECRET}

place.model.url=${URL_PYTHON}

url.frontend=${URL_FRONTEND}

spring.cloud.compatibility-verifier.enabled=false