package geo.track.jornada.enums;

public enum TipoJornada {
    AGENDAMENTO,
    CONFIRMAR_ENTRADA_AGENDADA,
    ENTRADA_EFETIVA,
    ENTRADA_EFETIVA_SEM_CADASTRO,

    ADICIONAR_ITEM_PRODUTO,
    ADICIONAR_ITEM_SERVICO, SAIDA_MATERIAL, ATUALIZAR_STATUS, DEFINIR_SAIDA_PREVISTA, DEFINIR_PAGAMENTO_REALIZADO, DEFINIR_NOTA_FISCAL_REALIZADA;
}
