package geo.track.jornada.enums;

public enum TipoJornada {
    AGENDAMENTO,
    CONFIRMAR_ENTRADA_AGENDADA,
    ENTRADA_EFETIVA,
    ENTRADA_EFETIVA_SEM_CADASTRO,

    ADICIONAR_ITEM_PRODUTO,
    ADICIONAR_ITEM_SERVICO;




}
